export const platforms = [
  { header: "x-vercel-id", name: "Vercel" },
  { header: "x-nf-request-id", name: "Netlify" },
  { header: "x-render-origin-server", name: "Render" },
  { header: "fly-request-id", name: "Fly.io" },
  { header: "x-railway-edge", name: "Railway" },
  { header: "x-github-request-id", name: "GitHub" },
  { header: "x-shopid", name: "Shopify" },
  { header: "x-wix-request-id", name: "Wix" },
  { header: "x-azure-ref", name: "Azure" },
  { header: "x-amz-cf-id", name: "AWS CloudFront", cdn: true },
  { header: "cdn-pullzone", name: "Bunny CDN", cdn: true },
  { header: "x-akamai-transformed", name: "Akamai" },
  { header: "cf-ray", name: "Cloudflare" },
  { header: "x-served-by", name: "Fastly" },
];

export const networks = [
  { org: "amazon", name: "AWS" },
  { org: "google", name: "Google" },
  { org: "microsoft", name: "Azure" },
  { org: "hetzner", name: "Hetzner" },
  { org: "digitalocean", name: "DigitalOcean" },
  { org: "ovh", name: "OVHcloud" },
  { org: "oracle", name: "Oracle Cloud" },
  { org: "akamai connected cloud", name: "Akamai / Linode" },
  { org: "akamai", name: "Akamai", cdn: true },
  { org: "ionos", name: "IONOS" },
  { org: "strato", name: "Strato" },
  { org: "netcup", name: "netcup" },
  { org: "scaleway", name: "Scaleway" },
  { org: "constant company", name: "Vultr" },
  { org: "cloudflare", name: "Cloudflare", cdn: true },
  { org: "fastly", name: "Fastly", cdn: true },
  { org: "bunnyway", name: "Bunny CDN", cdn: true },
  { org: "sucuri", name: "Sucuri", cdn: true },
  { org: "incapsula", name: "Imperva", cdn: true },
];
